### ISSUE TITLE
Plugin no longer works with API

### ISSUE THREAD

**Issue by ndtob** [SANdood/homebridge-purpleair#1]
It would appear the plugin is no longer working with the PurpleAir API.

[2019-11-9 07:56:42] ReferenceError: pmtoString is not defined
    at PurpleAirAccessory.updateData (/usr/local/lib/node_modules/homebridge-purpleair/index.js:155:54)
    at Request._callback (/usr/local/lib/node_modules/homebridge-purpleair/index.js:50:32)
    at Request.self.callback (/usr/local/lib/node_modules/request/request.js:185:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/request/request.js:1161:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:314:30)

**Comment by SANdood** [comment]
I fixed the typo - odd that nobody reported that before...

**Comment by ndtob** [comment]
Fixed and working!
